### ISSUE TITLE
Printing labels from different applications results in different spacing.

### ISSUE THREAD

**Issue by jfeust** [jordanbyron/prawn-labels#25]
When generating PDF's they all look like the same spacing when viewed on screen. When you go to print them however, depending on what application you are printing from, the spacing get's messed up and they do not print properly on the labels.

Apple Preview - Always seems to print OK.
Print from Chrome, Acrobat Reader, etc, causes spacing issues.  The other weird thing is that depending on the application, the spacing issues are different.

It seems to print differently from each program.

Here is a screenshot, all generated from the same label PDF, printed from different applications. One of these print fine on 5160 labels (the last one printed from apple preview), all the others don't.

![screen shot 2014-11-19 at 11 04 08 am](https://cloud.githubusercontent.com/assets/732877/5111159/d2eedcbc-6fdb-11e4-8239-835619e1c1d0.png)

**Comment by codeodor** [comment]
@jfeust how did you add the padding to the labels?  I'm running up against the same issue.

**Comment by codeodor** [comment]
Specifically I'm hoping to add a bit of padding to the left because that's where I'm noticing the cutoff.
