### ISSUE TITLE
Any plans to support prawn 2.0.0?

### ISSUE THREAD

**Issue by irobayna** [jordanbyron/prawn-labels#28]
Any plans to support prawn 2.0.0?

Thank you!

**Comment by jordanbyron** [comment]
Gem [updated](https://github.com/jordanbyron/prawn-labels/releases/tag/1.2.3) and pushed to [rubygems](https://rubygems.org/gems/prawn-labels/versions/1.2.3). Enjoy! :smile:

**Comment by irobayna** [comment]
@jordanbyron Thanks! :+1:
