### ISSUE TITLE
'avery5160' label offset slips when printing

### ISSUE THREAD

**Issue by annieogrady** [jordanbyron/prawn-labels#30]
I am on rails 4.0. 

I am able to print the PDF file and it looks great when saving as the PDF.  But as I print on the label sheet, after about the 5th row, the formatting of the label shifts (no longer aligned to the label on the sheet - but starts shifting up a little - so then starts printing offset from where is should print)

the Addresses I am printing are 3 lines.  Just wondering if there is something I need to do when print to then have the PDF render to fit the Label?

Is there logic that needs to be added if the addresses are only 3 lines (vs. 4)?

**Comment by jordanbyron** [comment]
Hey @annieogrady!

Assuming you are using Avery 5160 labels and your printer isn't shifting the paper around you shouldn't have to do anything special. Can you share the code you wrote with me so I can see if there is something going on there? All I need is the `Prawn::Labels.render` block and the generated PDF file.

**Comment by annieogrady** [comment]
Hi @jordanbyron - thanks for the quick response.  here is the code.


 
def create_campaign_labels
    quantity = 0
    @labels = Prawn::Labels.render(@contacts,
              :type => @type) do |pdf, contact|
      name = contact.name
      quantity = quantity + 1
      address_string_line1 = create_contact_address1_string(contact)
      address_string_line2 = create_contact_address2_string(contact)
      name = contact.name + "\n" + address_string_line1 +
             "\n" + address_string_line2
      pdf.text name
    end
      @print_campaign.pdf_created_at = Time.zone.now
      if @print_campaign.name?
        @name = "Labels " + @print_campaign.name + "-" +
                Time.zone.now.to_formatted_s(:short) + ".pdf"
      else
        @name = "AB Labels " + "-" + Time.zone.now.to_formatted_s(:short) + ".pdf"
      end
    file = @name
    send_data @labels, :filename => @name, :type => "application/pdf"
    @print_campaign.file = @name
    Util.log "FILE NAME #{file}"
    Util.log "FILE NAME #{@print_campaign.file}"
    @print_campaign.quantity = quantity


NB:  the Util.logs are there for a different issue.  I am also trying to use Carrierwave, if i add Mount (to .rb file), the whilst 'file' from PrawnGem comes out.  when i try to save, it is as @print_campaign.file, it is nil (raised a separate SO question as I think it is to do with Carrierwave - not prawn labels).

![annietestjpeg](https://cloud.githubusercontent.com/assets/4672615/9387367/34b4defe-472e-11e5-9e72-a513b6ccc258.jpg)


i have attached the output (that saves as a pdf but here saves as jpeg so i cold attach). couple of things:
- i do notice some extra space at the bottom. i have tried printing labels opposite end and same thing happens.  
- the spacing between address lines looks correct.
- columns are find.

**Comment by jordanbyron** [comment]
@annieogrady what is the value of `@type` in that method? You can find out by adding this line to your `create_campaign_labels` method and trying to generate the PDF. You should get an error message with the value of `@type`.

```ruby
def create_campaign_labels
  raise @type.inspect
  # ....
end
```

**Comment by annieogrady** [comment]
@jordanbyron  - "Avery5160"

**Comment by jordanbyron** [comment]
@annieogrady well that looks right to me. The only other thing I can think of is that the issue is with your printer's configuration. If it is adding additional margin to the page that would throw off the row spacing. You can try tweaking the values of the label until it generates a PDF that prints correctly:

```yaml
Avery5160:
    paper_size: LETTER
    top_margin: 36
    bottom_margin: 36
    left_margin: 15.822
    right_margin: 15.822
    columns: 3
    rows: 10
    column_gutter: 15
    row_gutter: 0
```

Note that those units are PostScript-Point (72 points per inch). Good luck!

**Comment by annieogrady** [comment]
@jordanbyron,

in terms of tweaking, where would i do that?
i am using rails - i tried to add the 'shrink to fit => true'  but i am getting an error.

many thanks.

**Comment by jordanbyron** [comment]
@annieogrady to manually adjust the margins of the PDF you'd have to do something like this:

```ruby
Prawn::Labels.types = {
  'Avery5160ADJUSTED' => {
    paper_size: 'LETTER'
    top_margin: 36
    bottom_margin: 36
    left_margin: 15.822
    right_margin: 15.822
    columns: 3
    rows: 10
    column_gutter: 15
    row_gutter: 0 }
}}

Prawn::Labels.generate("names.pdf", names, :type => "Avery5160ADJUSTED") do |pdf, name|
  pdf.text name
end
```

But keep in mind that now you're adjusting the output of the PDF so it will only work on __just__ your printer. Have you tried printing any of the test examples? You can try generating them by copying / pasting one of the test examples into your rails console or just download [this one](http://dropbox.jordanbyron.com/generic_labels.pdf). These labels are know to print correctly. Maybe even try saving your output PDF and print it to another printer or using a different PDF program. 

Good luck!

**Comment by annieogrady** [comment]
Hi Jordan,

Just to let you know - i tweaked this to a custom5160 to provide border (our users told us the font was too close to the top and side of label.  

here is my custom label in case anyone else has same issue:

Custom5160:
    paper_size: LETTER
    top_margin: 40
    bottom_margin: 36
    left_margin: 15.822
    right_margin: 15.822
    columns: 3
    rows: 10
    column_gutter: 30
    row_gutter: 15

**Comment by codeodor** [comment]
We had a problem with the 5160 printing as well. Tried it on 4 different printers using labels straight from Avery (as opposed to someone who said the template would be the same).

Here is what we ended up doing:

```ruby
Prawn::Labels.types["Avery5160Adjusted"] = Prawn::Labels.types["Avery5160"].dup
Prawn::Labels.types["Avery5160Adjusted"]["top_margin"] += 8
Prawn::Labels.types["Avery5160Adjusted"]["left_margin"] += 8
Prawn::Labels.types["Avery5160Adjusted"]["column_gutter"] += 3
Prawn::Labels.types["Avery5160Adjusted"]["row_gutter"] += 3
```

It printed fine at that point, though I still noticed it starting closer to the top of the label when it gets to the bottom of the page than when it does at the top. Maybe that means we should have tried a larger row gutter.

**Comment by krthi** [comment]
Any update on how to solve this issue?

**Comment by aaronkroontje** [comment]
> We had a problem with the 5160 printing as well. Tried it on 4 different printers using labels straight from Avery (as opposed to someone who said the template would be the same).
> 
> Here is what we ended up doing:
> 
> ```ruby
> Prawn::Labels.types["Avery5160Adjusted"] = Prawn::Labels.types["Avery5160"].dup
> Prawn::Labels.types["Avery5160Adjusted"]["top_margin"] += 8
> Prawn::Labels.types["Avery5160Adjusted"]["left_margin"] += 8
> Prawn::Labels.types["Avery5160Adjusted"]["column_gutter"] += 3
> Prawn::Labels.types["Avery5160Adjusted"]["row_gutter"] += 3
> ```
> 
> It printed fine at that point, though I still noticed it starting closer to the top of the label when it gets to the bottom of the page than when it does at the top. Maybe that means we should have tried a larger row gutter.

@codeodor Thanks for taking the time to post this 5 years ago, was exactly what I needed to fix my similar margin problem!
