### ISSUE TITLE
Any tips on positioning items within a label?

### ISSUE THREAD

**Issue by joshuairl** [jordanbyron/prawn-labels#34]
First off, thanks for building this - loving it so far.

Trying to figure out how to position things relative to the position of the label itself.

Prawn has "bounds" method that I would think would reveal this but it's not available within my code.

``` ruby
labels = Prawn::Labels.render(records, type: "Avery7160") do |pdf, record|
     bounds # nil
end
```

**Comment by jordanbyron** [comment]
Hey @joshuairl,

Thanks! Looks like you forgot to call `bounds` on `pdf`:

```ruby
labels = Prawn::Labels.render(records, type: "Avery7160") do |pdf, record|
  pdf.bounds # WIN!
end
```

You'll need to use the `pdf` variable to access any of prawn's methods.

**Comment by joshuairl** [comment]
Yeah, how do I get the bounds relative to the label though... it seems that pdf.bounds returns all same for each label.
For instance... bounds.top is always 133 in my particular instance even though there are different labels.
Make sense?

Thanks again for the help!

**Comment by joshuairl** [comment]
is Prawn::Labels.render vs .generate different in any way? Would it affect the block usage at all?

**Comment by joshuairl** [comment]
Ideally I'd like to be able to place an image with an "at:" position relative to the label box, not relative to the entire page.  Is this possible?

**Comment by jordanbyron** [comment]
@joshuairl yes it is possible. Just use `pdf.bounds`. For example if you want to place your image at the top right of each label do the following:

```ruby
fancy_names = ["Jordan", "Chris", "Jon", "Mike", "Kelly", "Bob", "Greg",
               "Jordan", "Chris", "Jon", "Mike", "Kelly", "Bob", "Greg",
               "Jordan", "Chris", "Jon", "Mike", "Kelly", "Bob", "Greg",
               "Jordan", "Chris", "Jon", "Mike", "Kelly", "Bob", "Greg",
               "Jordan", "Chris", "Jon", "Mike", "Kelly", "Bob", "Greg"]
image = open("http://jordanbyron.com/me.png")
image_size = 48

Prawn::Labels.generate(pdf_path, fancy_names, type: "Avery5160") do |pdf, name|
  pdf.stroke_bounds
  pdf.text name
  pdf.image image,
    at: [pdf.bounds.right - image_size, pdf.bounds.top ]
end
```

![screen shot 2015-12-02 at 3 00 47 pm](https://cloud.githubusercontent.com/assets/40662/11542478/80f108be-9905-11e5-838a-f6e5ea45adac.png)

**Comment by joshuairl** [comment]
Thanks for the extensive explanation.  You rock.
However, attempting to do the same with a text box or with `pdf.bounds.top+20` and for some reason the higher the number I add to the pdf.bounds.top the more negative it goes outside of the box above.  Confusing me!! haha

**Comment by jordanbyron** [comment]
@joshuairl No problem. Head over to http://prawnpdf.org/api-docs/2.0/ and familuarlize yourself with Prawn's docs. That should get you unstuck. Best of luck!
