### ISSUE TITLE
Position of the first label

### ISSUE THREAD

**Issue by tballarin** [jordanbyron/prawn-labels#35]
Hi, 
It's possible to declare the position of printing start?
To use paper where I already print element ?

Regards

**Comment by jordanbyron** [comment]
Just offset the data you feed into the label. For example if you wanted to start printing on the 3rd label just add 2 `nil` entries at the start of your array

```ruby
[nil, nil, "Jordan", "Marco"]
```

Then make sure you handle those blank records when generating labels. It's a bit of a hack but should work.
